### ISSUE TITLE
Questions about Hypervisor Network Configuration

### ISSUE THREAD

**Issue by spiritLHLS** [webvirtcloud/webvirtcloud#31]
I'm a complete novice at this, I've only used Proxmox and Kubevirt to open and use VMs before, but I'm happy to try new things.

Q1:

From https://webvirt.cloud/docs/installation/setup-hypervisor#for-all-supported-distributions 

```bash
nmcli conn modify br-ext ipv4.method manual +ipv4.addresses 192.168.50.10/24 # NEED TO CHANGE 192.168.50.10/24 TO MATCH YOUR CIDR
nmcli conn modify br-ext ipv4.method manual ipv4.gateway 192.168.50.1 # NEED TO CHANGE 192.168.50.1 TO YOUR GATEWAY IP
```

Should I fill in my public IPv4 address and gateway here?  
I retrieve them using the following commands:

```bash
ip addr show "$interface" | awk '/inet / {print $2}' | head -n 1
```

```bash
ip route | awk '/default/ {print $3}' | head -n 1
```

Are these commands correct?

Q2:

I want to configure two bridges: `eno1` and `eno2`.  
However, I only have one physical NIC. Does that mean the second bridge can be created solely for internal communication without binding to a physical NIC?

```bash
nmcli connection add type bridge ifname br-int con-name br-int ipv4.method disabled ipv6.method ignore
nmcli connection modify br-int bridge.stp no
nmcli connection modify br-int 802-3-ethernet.mtu 1500
nmcli connection up br-int
```

Q3:

Is NAT port binding supported for virtual machines? My IPV4 resources are very tight and I may not be able to assign full IPV4 addresses to each VM.

Thanks all!

**Comment by retspen** [comment]
Hello,
1. The `br-ext` bridge device is used to provide access to the public network (Internet).
2. You can use a single network interface for both bridges, but this will only work within the same node for private networking.
3. You can configure everything within your local network and enable port forwarding from the public network to your local environment. (We use this approach for development and testing as well.) For example, I use my laptop as a controller (running Docker) and a separate node (hypervisor) for virtual machines.

**Comment by spiritLHLS** [comment]
I got it, let me have a try

**Comment by spiritLHLS** [comment]
Due to some environmental issues, I forked and modified it to

https://github.com/spiritLHLS/webvirtcompute/blob/master/scripts/libvirt.sh

So that I could install successfully on almalinux 9.5, I modified the

- Loosely recognized version number
- Removed the use of TCP sockets in favor of the standard libvirtd service.
- All virsh commands have the -c qemu:///system parameter added to ensure connection to the correct hypervisor.

Does this meet your design requirements? Should I submit pull requests, or do you want to test it and make your own changes?

**Comment by retspen** [comment]
Hello,

I've fixed the version checking of the RHEL distribution, but I'm not sure of other changes you can use as options.

Thank you!

**Comment by spiritLHLS** [comment]
Fine

**Comment by spiritLHLS** [comment]
error: failed to connect to the hypervisor
error: Operation not supported: Cannot use direct socket mode if no URI is set. For more information see https://libvirt.org/kbase/failed_connection_after_install.html

As per your current new install script then it will report the error as above, I did not fix this after checking the official link.

**Comment by retspen** [comment]
Sorry, my bad. Now it fixed.

**Comment by spiritLHLS** [comment]
All works!

One last question, the description says 

```
WEBVIRTBACKED_IP=<you backend IP> # need put your backend IP
```

```
Configuring daemon (optional)
WebVirtCompute uses a configuration file to set up the daemon. The default configuration file is located at /etc/webvirtcompute/webvirtcompute.ini. You have to copy token and add it to WebVirtCloud admin panel when you add a new compute node.
```

Is the backend IP the IP of the server where I deployed the controller or the server where I deployed the hypervisor? I added a new node to the Computes page of the panel in admin, and I see a lot of mandatory fields, and the hostname is set as a mandatory field. Does this overwrite the hostname of my original machine, or do I have to fill in the actual hostname? Other than that I have no other questions at the moment.

**Comment by retspen** [comment]
Yes, WEBVIRTBACKED_IP means controller IP (fixed in README.md). The Hostname field is a simple field to identify your computer in the controller.

**Comment by spiritLHLS** [comment]
Other minor issue: some configurations are set to unavailable in /admin/size/, but these disabled configurations can be selected for resize after a client has opened a VM.

**Comment by spiritLHLS** [comment]
Some other suggestions: 
Controller found after installation that the backend container webvirtcloud-db-migration was not automatically deleted after startup and exit, it is suggested to delete it automatically.
Controller and Hypervisor are not the same node, if you add a Hypervisor node to Controller, it is recommended to have a test button to start the smallest instance to test if you can open a VM in Hypervisor, otherwise you don't know how to test and troubleshoot after adding it.
Currently, I can only open the VM on the machine where the Controller is deployed and the Hypervisor's node is not available in the Controller, and I can't find where I can troubleshoot it.

**Comment by retspen** [comment]
> Other minor issue: some configurations are set to unavailable in /admin/size/, but these disabled configurations can be selected for resize after a client has opened a VM.

If configuration disable for client it means you can't resize to low size

**Comment by retspen** [comment]
> Some other suggestions: Controller found after installation that the backend container webvirtcloud-db-migration was not automatically deleted after startup and exit, it is suggested to delete it automatically. Controller and Hypervisor are not the same node, if you add a Hypervisor node to Controller, it is recommended to have a test button to start the smallest instance to test if you can open a VM in Hypervisor, otherwise you don't know how to test and troubleshoot after adding it. Currently, I can only open the VM on the machine where the Controller is deployed and the Hypervisor's node is not available in the Controller, and I can't find where I can troubleshoot it.

The migration is using for update and next migrations after updating. If you open compute on admin side and you will see info like this without any errors it means you connected to hypervisor.

<img width="1257" alt="Image" src="https://github.com/user-attachments/assets/b247848e-0a39-4591-b1dd-e0e577969f84" />

**Comment by spiritLHLS** [comment]
> > Some other suggestions: Controller found after installation that the backend container webvirtcloud-db-migration was not automatically deleted after startup and exit, it is suggested to delete it automatically. Controller and Hypervisor are not the same node, if you add a Hypervisor node to Controller, it is recommended to have a test button to start the smallest instance to test if you can open a VM in Hypervisor, otherwise you don't know how to test and troubleshoot after adding it. Currently, I can only open the VM on the machine where the Controller is deployed and the Hypervisor's node is not available in the Controller, and I can't find where I can troubleshoot it.
> 
> The migration is using for update and next migrations after updating. If you open compute on admin side and you will see info like this without any errors it means you connected to hypervisor.
> <img alt="Image" width="1257" src="https://private-user-images.githubusercontent.com/688722/435363937-b247848e-0a39-4591-b1dd-e0e577969f84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUwNDU5MzUsIm5iZiI6MTc0NTA0NTYzNSwicGF0aCI6Ii82ODg3MjIvNDM1MzYzOTM3LWIyNDc4NDhlLTBhMzktNDU5MS1iMWRkLWUwZTU3Nzk2OWY4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQxOVQwNjUzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWI3ZjA5NTQyYzNkZWE4NGIxNjZmNGFjODUyNWJiMmE3ODhjOTBhYzZlNTVkODYzNGMyMWI3YjcwYmFjNjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r1vhYA3UYjZkendreCytVn2NtA0ILGopNR0wQkBvUCc">

I don't see it at the moment, where do I check the logs to troubleshoot the problem? Are there any daemons to query?

**Comment by retspen** [comment]
Simple way to check you can use`telnet` from controller to node:

```telnet <node ip> 8884```

Check daemon logs on a node you can use: 

```journalctl -xeu webvirtcompute```

**Comment by spiritLHLS** [comment]
> Simple way to check you can use`telnet` from controller to node:
> 
> `telnet <node ip> 8884`
> 
> Check daemon logs on a node you can use:
> 
> `journalctl -xeu webvirtcompute`

I got it, must use

```
firewall-cmd --zone=public --add-port=1-65535/tcp --permanent
firewall-cmd --zone=public --add-port=1-65535/udp --permanent
firewall-cmd --reload
```

in my node

**Comment by spiritLHLS** [comment]
> > Simple way to check you can use`telnet` from controller to node:
> > `telnet <node ip> 8884`
> > Check daemon logs on a node you can use:
> > `journalctl -xeu webvirtcompute`
> 
> I got it, must use
> 
> ```
> firewall-cmd --zone=public --add-port=1-65535/tcp --permanent
> firewall-cmd --zone=public --add-port=1-65535/udp --permanent
> firewall-cmd --reload
> ```
> 
> in my node

Some nodes are fine after doing so, but some nodes can't find out the problem in either of the two troubleshooting methods you provided, and the front-end reports an error:

Internal server error
Something went wrong on our end. Please try again later

Is there any other way to troubleshoot?

**Comment by retspen** [comment]
Can you show logs in the controller?

```docker compose logs backend```

**Comment by spiritLHLS** [comment]
> Can you show logs in the controller?
> 
> `docker compose logs backend`

```
root@rabbit:~/webvirtcloud# docker-compose logs backend
webvirtcloud-backend  | [2025-04-21 01:11:55 +0000] [1] [INFO] Starting gunicorn 20.1.0
webvirtcloud-backend  | [2025-04-21 01:11:55 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
webvirtcloud-backend  | [2025-04-21 01:11:55 +0000] [1] [INFO] Using worker: sync
webvirtcloud-backend  | [2025-04-21 01:11:55 +0000] [7] [INFO] Booting worker with pid: 7
```
root@rabbit:~/webvirtcloud# lsof -i:8000
root@rabbit:~/webvirtcloud# docker ps -a
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS                      PORTS                                                                                             NAMES
377522f525c7   webvirtcloud:backend    "celery -A webvirtcl…"   19 minutes ago   Up 18 minutes                                                                                                                 webvirtcloud-scheduler
134062e1dfd1   webvirtcloud:backend    "gunicorn webvirtclo…"   19 minutes ago   Up 18 minutes                                                                                                                 webvirtcloud-backend
ee8343f45d2b   webvirtcloud:backend    "celery -A webvirtcl…"   19 minutes ago   Up 18 minutes (healthy)                                                                                                       webvirtcloud-worker
0b73f03df5e5   webvirtcloud:backend    "python3 manage.py n…"   19 minutes ago   Up 18 minutes                                                                                                                 webvirtcloud-novnc
f5663664a1b2   webvirtcloud:backend    "python3 manage.py m…"   19 minutes ago   Exited (0) 18 minutes ago                                                                                                     webvirtcloud-db-migration
07121b040f1f   rabbitmq:3.10.13        "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes (healthy)     4369/tcp, 5671-5672/tcp, 15691-15692/tcp, 25672/tcp                                               webvirtcloud-rabbitmq
256b77d592ef   mariadb:10.6.10         "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes (healthy)     3306/tcp                                                                                          webvirtcloud-mariadb
f210443ed389   webvirtcloud:frontend   "caddy run --config …"   19 minutes ago   Up 19 minutes               0.0.0.0:80->80/tcp, [::]:80->80/tcp, 0.0.0.0:443->443/tcp, [::]:443->443/tcp, 443/udp, 2019/tcp   webvirtcloud-frontend
```

**Comment by retspen** [comment]
I mean when you have error, can you show backend logs?

**Comment by retspen** [comment]
You need to enable DEBUG mode:

```bash
docker compose exec backend sh
nano webvirtcloud/settings/production.py # or you can use "vim" for edit
```

change `DEBUG=False` to `DEBUG=True`

```bash
docker compose restart backend
```

than try again and show logs

**Comment by spiritLHLS** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.10/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python3.10/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python3.10/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lib/python3.10/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/backend/webvirtcloud/urls.py", line 27, in <module>
    from drf_yasg import openapi
ModuleNotFoundError: No module named 'drf_yasg'
```

> You need to enable DEBUG mode:
> than try again and show logs

ModuleNotFoundError

**Comment by retspen** [comment]
The next step:

```bash
docker compose exec sh
UV_PROJECT_ENVIRONMENT=/usr/local uv sync --dev
```

and than reload backend

```bash
docker compose restart backnd
```

and show the same logs

**Comment by spiritLHLS** [comment]
```
[2025-04-21 08:00:06 +0000] [7] [INFO] Booting worker with pid: 7
Internal Server Error: /admin/compute/3/overview
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] Name has no usable address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd4f5176320>: Failed to establish a new connection: [Errno -5] Name has no usable address
```

**Comment by spiritLHLS** [comment]
> ```
> [2025-04-21 08:00:06 +0000] [7] [INFO] Booting worker with pid: 7
> Internal Server Error: /admin/compute/3/overview
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/local/lib/python3.10/socket.py", line 967, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -5] Name has no usable address
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 716, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
>     self.sock = conn = self._new_conn()
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd4f5176320>: Failed to establish a new connection: [Errno -5] Name has no usable address
> ```

I know what happened, hostname must use Hypervisor Node IPV4 !

**Comment by retspen** [comment]
Yes! You can use hostname too but controller DNS doesn't know this name

**Comment by spiritLHLS** [comment]
I think when deploying the hypervisor, there was no hint that the user had to bind a domain name and then fill in the Controller with that domain name, leading me to think that it was just a “contents of /etc/hostname on the system”, and that the user should be told to fill in either the IP address or the address of the domain name to which they are bound (with the protocol header removed).

**Comment by retspen** [comment]
I will add check for this later

**Comment by spiritLHLS** [comment]
I have seen support for customizing the qcow2 images for VMs in admin's panel, it would be nice to have import instructions for this, I have sets of all the major images used on proxmoxve (with qemu-agent and cloud-init pre-installed).

**Comment by retspen** [comment]
We use don't support proxmox images and we don't support export and import images.

**Comment by spiritLHLS** [comment]
> We don't support proxmox images and we don't support export and import images.

Ok, but in that case your Debian12 image has the problem of not setting SSH login available password login and ROOT login available, I guess other images have similar problems, I was going to fix it myself, but in that case I'll have to leave it to you.

**Comment by spiritLHLS** [comment]
> If ssh and password doesn't work it means VM can't connect to metadata service (169.254.169.254). Check firewall rules for metedata service. Is correct IP address for virtual machine? You have own network topology that is difficult to say what doesn't work.

It is about `/etc/ssh/sshd_config` setting, your default setting is wrong.

**Comment by spiritLHLS** [comment]
It's actually connectable, it's just that your default settings prevent me from logging in with a password using the root user (when logging in remotely), and logging in on VNC is no problem at all

> We don't have any settings for SSH, that why you need check connection to metadata service

![Image](https://github.com/user-attachments/assets/4499c22d-3489-4a57-87c0-429e39a2862e)

**Comment by retspen** [comment]
You can try to get info:

```bash
curl http://169.254.169.254/metadata/v1.json
```

**Comment by spiritLHLS** [comment]
![Image](https://github.com/user-attachments/assets/3a80cb4f-0f83-4714-a148-32031c6f79ce)

> You can try to get info:
> 
> curl http://169.254.169.254/metadata/v1.json

**Comment by retspen** [comment]
Your backend doesn't understand which IP using for VM, I think because backend see gateway IP for all VMs that you created.

**Comment by spiritLHLS** [comment]
> Your backend doesn't understand which IP using for VM, I think because backend see gateway IP for all VMs that you created.

Where is this part fixed? firewalld or nmcli?

**Comment by spiritLHLS** [comment]
> ![Image](https://github.com/user-attachments/assets/3a80cb4f-0f83-4714-a148-32031c6f79ce)
> 
> > You can try to get info:
> > curl http://169.254.169.254/metadata/v1.json

https://github.com/webvirtcloud/webvirtbackend/blob/0977b2f07931d95af7e61589c1c15d2b3a57fd9c/metadata/v1/urls.py

I don't see anything about using metadata to configure SSH rules, if I don't change `/etc/ssh/sshd_config` then remote logins or even logins on the host using the VM's IP will be denied, I need to change 

```
PermitRootLogin prohibited-password
#PasswordAuthentication no
``` 

to 

``` 
PermitRootLogin yes
PasswordAuthentication yes
```

**Comment by spiritLHLS** [comment]
![Image](https://github.com/user-attachments/assets/7ae1bece-abe8-46ea-9893-d40c098f3f0e)

https://github.com/webvirtcloud/webvirtbackend/blob/0977b2f07931d95af7e61589c1c15d2b3a57fd9c/virtance/utils.py#L67

The function says elapsed_time = 0, but the variable is never updated in the loop, meaning that while elapsed_time < timeout: it's actually a dead loop that never exits, is it wrong?

**Comment by retspen** [comment]
> ![Image](https://github.com/user-attachments/assets/7ae1bece-abe8-46ea-9893-d40c098f3f0e)
> 
> https://github.com/webvirtcloud/webvirtbackend/blob/0977b2f07931d95af7e61589c1c15d2b3a57fd9c/virtance/utils.py#L67
> 
> The function says elapsed_time = 0, but the variable is never updated in the loop, meaning that while elapsed_time < timeout: it's actually a dead loop that never exits, is it wrong?

What is not working for this time?

**Comment by 60753b9e** [comment]
I noticed that `/etc/cloud/cloud.cfg` seems to define disable_root as true, and webvirt's priority is at 99, which seems to cause webvirt's disable_root property to be ignored by cloud-init.

**Comment by retspen** [comment]
> I noticed that `/etc/cloud/cloud.cfg` seems to define disable_root as true, and webvirt's priority is at 99, which seems to cause webvirt's disable_root property to be ignored by cloud-init.
> 
> The image is debian12

Cloud-init settings for `WebVirtCloud`:

```bash
root@debian12:~# cat /etc/cloud/cloud.cfg.d/99-webvirtcloud.cfg
datasource_list: [ WebVirtCloud, None ]
ssh_pwauth: true
disable_root: false
network:
  config: disabled
```
